### PR TITLE
Line endings normalization rule in .gitattributes

### PR DESCRIPTION
**Pull request by lucernae**
Regarding Issue  #660

Add some attributes in .gitattributes.
The following are expected after this fix:
1. When Windows user doing a checkout, the line endings will follow the rule in their repository (core.autocrlf)
2. When Windows user doing a commit or push, the line endings will follow Unix style (LF), except for *.bat files (always CRLF)
3. Some of the files are set as binary to avoid falsely attributed as text, like images and fonts.

### CODE REVIEW

**Comment by akbargumbira** [comment]
hmm, isn't the line ending style configured in the git client? IIRC, using git bash windows, I can configure it..

**Comment by akbargumbira** [comment]
oh, just read the issue. So it's for avoiding windows developer commiting CRLF. I thought you have problem setting on windows.

**Comment by lucernae** [comment]
Well, @ismailsunni assigned me this, so I just following his direction and @timlinux 's comment

**Comment by timlinux** [comment]
LGTM - but please update your tree and ensure tests pass on travis / jenkins before merging.

Thanks

Tim

**Pull request merged**
