### PR TITLE
add encoding to UTF8 about layers #1159

### PR DESCRIPTION
**Pull request by Gustry**
see #1159  - add encoding to UTF8 about layers

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM - please merge when ready - thanks!

**Comment by ismailsunni** [comment]
hi @timlinux @Gustry 

I'm not sure about this. The last time, I tried similar solution, but it ends up with an error if we try to play with UTF8 character else where.

Perhaps, we can make a unit test related to UTF8 character first before merging, i.e. create a unit test with UTF8 character for the file name (or even the layer name, keyword, and so on)

cc @akbargumbira

**Comment by akbargumbira** [comment]
Hi, yes, from looking at the codes (have not tried this PR yet), pretty sure that this is only a partial solution. This will not fix e.g the case when the data itself has a non-ASCII character..

**Comment by timlinux** [comment]
Hi

Yes it is acknowledged that it is only a partial solution - if fixes an unhandled exception on @Gustry 's computer when using the new developer mode 'load standard layers' button. 

Regards

Tim

**Comment by akbargumbira** [comment]
Can one of the admins verify this patch?

**Comment by akbargumbira** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
