### PR TITLE
Wizard text string tweaks - do not merge

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
text string tweaks - but something is broken

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux - grateful if you can take a look at this.
I get the following error if i try to assign kw to buildings 
```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 3647, in on_pbnNext_released
    self.set_widgets_step_kw_field()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 1176, in set_widgets_step_kw_field
    subcategory['name'])
TypeError: not all arguments converted during string formatting


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, 313a6bc

Python path: ['C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\bin', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\arcpy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\ArcToolbox', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/AIFDR_ADMIN/.qgis2//python', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\inasafe', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', 'C:/WorkSpace/InaSAFE Testing/InaSAFE 3.2']
```

**Comment by timlinux** [comment]
We also get these errors from travis:

```
#554 Test for qgis translations. ... ok
======================================================================
ERROR: test_existing_complex_keywords (inasafe.safe.gui.tools.test.test_wizard_dialog.WizardDialogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 535, in test_existing_complex_keywords
    self.select_from_list_widget('KRB', dialog.lstFields)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 134, in select_from_list_widget
    raise Exception(message)
Exception: There is no KRB in the list widget
======================================================================
ERROR: Test if keywords already exist.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 463, in test_existing_keywords
    self.check_current_text('FLOODPRONE', dialog.lstFields)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 115, in check_current_text
    current_text = list_widget.currentItem().text()
AttributeError: 'NoneType' object has no attribute 'text'
======================================================================
ERROR: Checking that it works for unknown unit.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 808, in test_unknown_unit
    self.check_current_text('KRB', dialog.lstFields)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 115, in check_current_text
    current_text = list_widget.currentItem().text()
AttributeError: 'NoneType' object has no attribute 'text'
======================================================================
FAIL: Test for line layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 1115, in test_integrated_line
    self.check_list(expected_fields, dialog.lstFields)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected ['NAME', 'OSM_TYPE', 'TYPE'] but I got []
======================================================================
FAIL: Test for polygon layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 1167, in test_integrated_polygon
    self.check_current_step(step_kw_field, dialog)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 103, in check_current_step
    self.assertEqual(expected_step, current_step, message)
AssertionError: Expected 7 but I got 4
======================================================================
FAIL: Test how the widgets work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 344, in test_keywords_creation_wizard
    self.check_current_step(step_kw_field, dialog)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 103, in check_current_step
    self.assertEqual(expected_step, current_step, message)
AssertionError: Expected 7 but I got 6
======================================================================
FAIL: Test for case existing building generic unit for structure.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 733, in test_unit_building_generic
    self.check_current_step(step_kw_field, dialog)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 103, in check_current_step
    self.assertEqual(expected_step, current_step, message)
AssertionError: Expected 7 but I got 4
```

**Comment by ismailsunni** [comment]
LGTM.
Please merge if it's ready.
I want to push the new strings to transifex on 00.00 UTC :smiley:  [Today is string freeze] , so that we can start translating it tomorrow.

**Comment by Charlotte-Morgan** [comment]
ok - let me check for any disasters before i merge

**Pull request merged**
