### PR TITLE
Fix #1863: Rerun function with the same param

### LINKED ISSUE #1863: Rerun function with the same parameters
Right now when we run functions with updated parameters the second time, it won't use the previous parameters.

### PR DESCRIPTION
**Pull request by lucernae**
Running IF after the first time will uses the same parameters already defined in the first run

### CODE REVIEW

**Comment by lucernae** [comment]
test this please, jenkins

**Comment by lucernae** [comment]
Test this please, jenkins.

**Comment by lucernae** [comment]
test this please, jenkins

**Comment by akbargumbira** [comment]
test this please, jenkins

**Pull request merged**
