### PR TITLE
add new metadata support

### LINKED ISSUE #1246: We need to implement ISO 19115 support (Phase 2)
# Requirements

- [ ] Write keywords in GeoJson / JSON to the additional data field
in a cdata block (instead of old KVP format)

# See also
#1244, #1245, #1128

### LINKED ISSUE #1247: We need to implement ISO 19115 support (phase 3)
# Requirement

- [ ] Implement more complete metadata, as per pervasive metadata RFC
- [ ] Figure out the boundaries between using additional data and standard iso 19115 fields (or duplicate the data in both places)
- [ ] By the end of this phase any other client app should be able to read the keywords defined in the iso tags and provide a sensible description of the dataset.
- [ ] InSAFE can retrieve comprehensive data for an impact layer and reconstruct any reports or even the analysis itself
- [ ] Come up with a plan to e.g. fall back to iso if an element is not present in our json structure
- [ ] Weigh up writing a complete iso parser with only a minimal supplementary fields entry versus a minimal iso document with only core fields

# See also
#1244, #1245, #1147 and #1128

### LINKED ISSUE #1316: We need to define provenance metadata for impact functions
# Problem 

With reference to #1128 we need to define formally what metadata will be persisted in the impact layer keywords. In the RFC we defined these as a discussion starting point:

```json
impact_functions_provenance = {
  'start_time' : '20140714_060955',
  'finish_time' : '20140714_061255',
  'hazard_layer' : 'path/to/hazard/layer',
  'exposure_layer' : 'path/to/exposure/layer',
  'impact_function_id' : 'impact_function_id',
  'impact_funcstion_version' : '2.1',
  'host_name' : 'my_computer',
  'user' : 'my_user',
  'qgis_version' : '2.4',
  'gdal_version' : '1.9.1',
  'qt_version' : '4.5',
  'pyqt_version' : '5.1',
  'os' : 'ubuntu 12.04',
  'inasafe_version' : '2.1'
  'exposure_pixel_size' : '0.1',
  'hazard_pixel_size' : '0.2',
  'impact_pixel_size' : '0.1',
  'analysis_extent' : [0, 1, 2, 2],
  'parameter' : 'dictionary for parameter'
  'inasafe_version' : '2.1'
}
```

# Proposed solution

* Marco to refine this list and get agreement from @Charlotte-Morgan, and other stake holders, and then ensure that each impact functio writes these out to its metadata. 
* IF metadata should be parsable so we can retrieve these facts again easily in subsequent sessions.
* IF metadata should be passed through to the reporting context so that any token can be used in a print layout
* IF tokens should be well documented so that composer designers can understand what keywords are available to them

### LINKED ISSUE #1626: We need an Assessment class
"InaSAFE must provide a rich metadata class that can store the state of every aspect of an analysis and be used to support rich reporting and (in the future) repeatable execution of the same analysis"

This class should provide properties for *all of the properties* for an analysis from end to end. It should have helper methods to read and write itself to disk in xml and to write to json (and in future other formats).

This class should ultimately replace the old keywords implementation which should be scrubbed / removed from the code tree when Assessment class is finalised.

@lucernae to collaborate on this with Marco

### PR DESCRIPTION
**Pull request by mbernasocchi**
add ISO metadata support
This PR introduces a new metadata system to allow storing per layer rich metadata in memory.
The metadata can then be saved in XML or JSON format to a file or into a local sqlite DB 

Closes #1626
Closes #1316
Closes #1246
Closes #1247

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@ismailsunni, @timlinux told me to have a look with you for integrating it. 
the first thing we need to do is to extend [BaseMetadata._standard_properties] (https://github.com/AIFDR/inasafe/pull/2165/files#diff-4b86e2b49707b5574bcc7e4e0e6e8c19R61) with all the needed keywords.

**Comment by ismailsunni** [comment]
@mbernasocchi does `all the needed keywords` mean the keywords that currently used in the .keywords file? (e.g. layer_mode, layer_purpose, etc)

**Comment by ismailsunni** [comment]
For layer's keywords:
##### mandatory keywords
- layer_purpose
- layer_mode
- layer_geometry
- keyword_version

##### mandatory keywords for hazard layer
- hazard_category
- hazard
- continuous_hazard_unit
- vector_hazard_classification
- raster_hazard_classification

##### mandatory keywords for exposure layer
- exposure
- exposure_unit

##### mandatory keywords for aggregation layer
- aggregation attribute
- adult ratio attribute
- adult ratio default
- elderly ratio attribute
- elderly ratio default
- female ratio attribute
- female ratio default
- youth ratio attribute
- youth ratio default

##### Not mandatory keywords
- title
- license
- scale
- source
- url

For Impact Layer's keywords, you can look at #1316 as a starting point. We can enhance it later.

For my own note, I need to add documentation for these keywords (especially related to hazard, exposure, and aggregation layers)

**Comment by mbernasocchi** [comment]
@ismailsunni are those mandatory keywords also for impact layers?

layer_purpose
layer_mode
layer_geometry
keyword_version

**Comment by mbernasocchi** [comment]
and the: Not mandatory keywords

title
license
scale
source
url

**Comment by ismailsunni** [comment]
hi @mbernasocchi 

All mandatory:
layer_purpose  ---> yes, but need to add another value for it (beside the current hazard, exposure, and aggregation). Perhaps impact_layer or just impact.
layer_mode --> yes
layer_geometry --> yes
keyword_version --> yes

Not mandatory:
title
license
scale
source
url

but we can add automatically to fill it. For example : source = InaSAFE, title = the title from the IF, etc.

**Comment by mbernasocchi** [comment]
@ismailsunni 
layer_purpose ---> yes, but need to add another value for it (beside the current hazard, exposure, and aggregation). Perhaps impact_layer or just impact.

this is not really clear to me

**Comment by ismailsunni** [comment]
@mbernasocchi 

sorry. What I mean is the impact layer need layer_purpose (to differentiate with the other layer). But currently, we don't have suitable value for it yet (we only have hazard, exposure, and aggregation). We can add another possible value to indicate that it is an impact layer. For example layer_purpose=impact.

**Comment by mbernasocchi** [comment]
Hi @ismailsunni ok, I understand, so basically whit the new metadata system layer_purpose is obsolete because it is the same as the class name of the metadatatype:
ImpactLayerMetadata, AggregationLayerMetadata, HazardLayerMetadata, ExposureLayerMetadata

**Comment by ismailsunni** [comment]
@mbernasocchi yes, exactly like that.

**Pull request merged**
