### PR TITLE
fix #2313 - Use sensible ordering for keywords in dock.

### LINKED ISSUE #2313: UI: We need consistent user facing terminology
We have made some massive steps in developing terminology to help users understand their data and the impact functions but we still have a bit of 'geek speak' that may not make sense to users.

I propose we tweak the words so that user facing terminology is consistent and may not be the same words used by developers in the code. This should have no impact on code or how things work.

I propose that we match the question asked in the KW wizard with the keywords report in the dock
that we match the metadata and training materials too :)

Below is a sample of the current wording and the proposed wording for 3 examples. there are also minor changes to order of items in the dock report.

Why - I think it will make the link between steps in the KW Wizard and the key words more intuitive and make it easier to write training materials

image

# cc
@samnawi @fredychandra @iyan31 @adissadis

### PR DESCRIPTION
**Pull request by timlinux**
fix #2313 - Use sensible ordering for keywords in dock.

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
looks good - can we be a little more specific to separate data fields from metadata fields?
See suggestion in #2313

**Comment by samnawi** [comment]
LGTM, but with some note that I've write in #2313.
And I prefer to make "Field" and "Attribute values" closest / adjacent, not like this picture
selection_204

Thank you

**Comment by timlinux** [comment]
Here is a little video showing the keywords rendered for each of the standard test datasets:

https://youtu.be/SJVmzJfgRLA

**Comment by timlinux** [comment]
@ismailsunni please review

**Comment by ismailsunni** [comment]
LGTM

**Pull request merged**
