### PR TITLE
Papercuts

### PR DESCRIPTION
**Pull request by timlinux**
* enable gitter notifications in travis build
* Remove text saying 'click for details' in error dialog

### CODE REVIEW

**Comment by timlinux** [comment]
Travis failing with these two errors:

```
======================================================================
FAIL: Test we can send error messages to the message viewer.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/widgets/test/test_message_viewer.py", line 96, in test_error_message
    self.assertEqual(text, expected_result)
AssertionError: u'*****Problem    The following problem(s) were encountered whilst running the analysis. - Exception*****Suggestion    You can try the following to resolve the issue: - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release. - Check the InaSAFE documentation to see if you are trying to do something unsupported. - Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved. - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.*****Details    These additional details were reported when the problem occurred. - Something went wrong*****Diagnostics' != '*****Problem    The following problem(s) were encountered whilst running the analysis. - Exception*****Suggestion    You can try the following to resolve the issue: - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release. - Check the InaSAFE documentation to see if you are trying to do something unsupported. - Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved. - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.*****Details    These additional details were reported when the problem occurred. - Something went wrong*****Diagnostics (click for details)'
-------------------- >> begin captured logging << --------------------
InaSAFE: DEBUG: Error message event
InaSAFE: DEBUG: Dynamic message event
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: Test error message works when there is a static message in place.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/widgets/test/test_message_viewer.py", line 107, in test_static_and_error
    self.assertEqual(text, expected_result)
AssertionError: u'Hi*****Problem    The following problem(s) were encountered whilst running the analysis. - Exception*****Suggestion    You can try the following to resolve the issue: - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release. - Check the InaSAFE documentation to see if you are trying to do something unsupported. - Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved. - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.*****Details    These additional details were reported when the problem occurred. - Something went wrong*****Diagnostics' != 'Hi*****Problem    The following problem(s) were encountered whilst running the analysis. - Exception*****Suggestion    You can try the following to resolve the issue: - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release. - Check the InaSAFE documentation to see if you are trying to do something unsupported. - Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved. - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.*****Details    These additional details were reported when the problem occurred. - Something went wrong*****Diagnostics (click for details)'
-------------------- >> begin captured logging << --------------------
InaSAFE: DEBUG: Error message event
InaSAFE: DEBUG: Dynamic message event
--------------------- >> end captured logging << ---------------------
```

**Comment by timlinux** [comment]
@ismailsunni please review

**Comment by timlinux** [comment]
@Charlotte-Morgan you might want to take a look at the updated README too...

**Comment by timlinux** [comment]
I'll merge - we can always tweak readme etc again as needed.

**Comment by Charlotte-Morgan** [comment]
where do i find the readme

**Comment by ismailsunni** [comment]
(A late) LGTM

@Charlotte-Morgan you can read it https://github.com/AIFDR/inasafe/blob/develop/README.md or in the main page of InaSAFE repo.

**Pull request merged**
