### PR TITLE
Fix 2111

### PR DESCRIPTION
**Pull request by ismailsunni**
Fixing #2111 and PEP8.

### CODE REVIEW

**Comment by ismailsunni** [comment]
jenkins, test this please

**Comment by ismailsunni** [comment]
test this please, jenkins

**Comment by ismailsunni** [comment]
@lucernae can you review this small PR?

**Comment by timlinux** [comment]
LGTM thanks

**Comment by lucernae** [comment]
LGTM about the realtime part, @ismailsunni :+1:

**Pull request merged**
