### PR TITLE
Land cover impact

### PR DESCRIPTION
**Pull request by wonder-sk**
Implemented as polygon hazard - polygon land cover exposure impact function - as suggested in #1216

Calculates affected and total area per each land cover type in the analysis area.

Only affected area are written to the resulting impact layer. It is possible to write also not affected areas, at the expense of extra processing time necessary for that (the code for that is currently commented out).

The impact function currently does not consider different classes of hazard.

Styling of resulting layer uses red border and no fill (so the fill color of land cover types from original layer can be seen).

Tested with artificial data and land cover of Kabupaten Bojonegoro as linked in #1216. (NOTE: the Bojonegoro shapefile has some duplicate polygon features, so total area reported by the IF is greater than the analysis area).

I am not very familiar with the whole metadata / keywords / parameters sub-system, so that area will need extra focus during the review. There are few TODOs where I would appreciate reviewer's comments.

Bojonegoro land cover + artificial hazard:
image

Artificial data:
image

### CODE REVIEW

**Comment by ismailsunni** [comment]
Hi @wonder-sk 
This looks great.
Last thing to do is adding percentage for each land cover type as they requested.

Thank you...

**Comment by wonder-sk** [comment]
@ismailsunni thanks for the review. added the percentages now.

I have realized there is an issue with how InaSAFE determines the analysis area as the intersection of hazard and exposure layers. For area analysis like this one, it makes more sense to use full extent of exposure layer (optionally intersected with user's analysis extent). Otherwise the total areas for individual land covers are misleading. Consider the case with artificial data - the total areas should read: Water = 199.5, Population = 399.1, Forest = 199.5, Meadow = 99.8. The total affected area is then reported to be ~86%, while the true affected area was supposed to be ~33%.

Any ideas how to deal with that? Add a piece of metadata to the impact function stating "ignore hazard extent when calculating analysis extent?

**Comment by wonder-sk** [comment]
Also, what to do with the failing wizard-related unit tests? Should be wizard updated to include land cover analysis or just fix the tests so they don't complain?

I am also a bit lost what's wrong with the last failing test related to metadata - any clue?
http://jenkins.inasafe.org/job/pull-request/619/testReport/junit/workspace.safe.impact_functions.test.test_impact_function_manager/TestImpactFunctionManager/test_hazards_for_layer/

**Comment by ismailsunni** [comment]
Hi @wonder-sk 
For the failing tests, it's alright. We can just update the  expected value in the test. The wizard automatically include land cover.

For the missleading, I think we should ask @timlinux for his opinion.

**Comment by wonder-sk** [comment]
The failing test in Travis is caused by the fact that ubuntugis-unstable is still at QGIS 2.8.1 which contains a bug causing distances and areas to be computed as zero. This has been already fixed in QGIS 2.8.2 (released on May 10).

@timlinux is it OK to merge that to experimental branch anyway?

**Comment by timlinux** [comment]
Hi

+1 to merge to experimental thanks

**Comment by wonder-sk** [comment]
Merged to experimental branch.

**Pull request closed without merging**
