### PR TITLE
Issue #1621. Fix pep8 use conventional function definition rather than l...

### PR DESCRIPTION
**Pull request by cchristelis**
...ambdas

### CODE REVIEW

**Comment by cchristelis** [comment]
A pull request that I tested out had gotten into this branch's history. So I had to roll the changes back and re-created the pull.

**Comment by akbargumbira** [comment]
Can one of the admins verify this patch?

**Comment by akbargumbira** [comment]
Can one of the admins verify this patch?

**Comment by akbargumbira** [comment]
ok to test

**Comment by cchristelis** [comment]
Pep8 passes on travis tests have timed out on, but they tests pass locally. I'm going to commit.

**Pull request merged**
