### PR TITLE
Fix keywords editor

### PR DESCRIPTION
**Pull request by lucernae**
Regarding issue #1281:

Bug:
XML ISO Metadata file wasn't read if the .keywords file didn't exist.

Fix:
Load from XML file instead if the .keywords file didn't exist.

### CODE REVIEW

**Comment by akbargumbira** [comment]
Can one of the admins verify this patch?

**Comment by akbargumbira** [comment]
Can one of the admins verify this patch?

**Comment by ismailsunni** [comment]
LGTM

**Comment by timlinux** [comment]
LGTM

**Pull request merged**
