### PR TITLE
In progress updated for #1975

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
edit aggregation definition

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM

**Comment by Charlotte-Morgan** [comment]
so what happens next @timlinux

**Comment by timlinux** [comment]
Well although your changes looked good to me, they didnt to Jenkins:

screen shot 2015-06-09 at 22 43 28

screen shot 2015-06-09 at 22 44 13

One error is a pep8 violation - I will comment in the diff where it is. The other is a break for osm downloader - we should ask @Gustry to look into why it is failing that test.

**Comment by timlinux** [comment]
Ii had a look at the pep8 error - its not because of your changes - so its just a question of the failing test and feedback from @Gustry

**Comment by Gustry** [comment]
This test has been fixed and merged this morning.
If you merge develop into your branch, this error should disappeared. Sorry about that.

**Comment by timlinux** [comment]
Thanks @Gustry

**Comment by timlinux** [comment]
And the PEP8 is fixed in #2027

**Pull request merged**
