### PR TITLE
add IDP layer to test data

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by timlinux** [comment]
Please check make ip-audit works too before merging.

Thanks

**Comment by Gustry** [comment]
I've run ``make data_audit``, I've fixed for potential idp. But this command is broken for buildings.dbf and generic_continuous_flood.asc

**Comment by akbargumbira** [comment]
Sorry, I think I forgot to add the lic files for those data. Please make
those missing lic files for me :)

On Wed, Jun 24, 2015 at 3:04 PM, Etienne Trimaille <notifications@github.com
> wrote:

> I've run make data_audit, I've fixed for potential idp. But this command
> is broken for buildings.dbf and generic_continuous_flood.asc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AIFDR/inasafe/pull/2063#issuecomment-114774651>.
>



-- 

*-------------------*

*Akbar Gumbira*
*Software Engineer*
*Geospatial, NLP, Data Mining, Machine Learning, Artificial Intelligence*

**Comment by Gustry** [comment]
Hi @akbargumbira, no problem, it's done ;-)

**Pull request merged**
