### PR TITLE
Fix zero impact exception

### PR DESCRIPTION
**Pull request by lucernae**
Don't merge it yet.

Trying to handle zero impact in every IF.

### CODE REVIEW

**Comment by lucernae** [comment]
Possible IF:
- [ ] Flood Raster Roads
- [ ] Flood Vector Roads
- [ ] Earthquake Vector Building
- [ ] Earthquake Vector Roads
- [ ] Generic IFs

**Comment by timlinux** [comment]
Is this ready for review & merge yet?

**Comment by lucernae** [comment]
Ah I forgot about this. Could you review this. I think I already covered IFs I can think of

**Comment by timlinux** [comment]
The current implemented changes all look fine to me, LGTM

**Pull request merged**
