### PR TITLE
 Logo, icon and font update

### PR DESCRIPTION
**Pull request by MariaSolovyeva**
- Icon.svg for the icon bar
- InaSAFE logo and InaSAFE url logo
- Ubuntu font

### CODE REVIEW

**Comment by timlinux** [comment]
Thanks for this @MariaSolovyeva - testing now. Can you also update the toolbar icons to use the monochrome gunungan (InaSAFE) icon in the background please?

**Comment by timlinux** [comment]
screen shot 2015-08-21 at 09 41 58

To clarify above comment, the icons listed in the screenshot should all use the monochrome gunungan - so these need updating:

* Global minimum needs configuration
* Minimum needs tool

I was also looking for a bit more of a radical makeover - I want the dock to look the same as the new web sites as much as possible.

Thanks!

**Comment by MariaSolovyeva** [comment]
Hello Tim,

OK, I'm working on it now

**Comment by timlinux** [comment]
@Charlotte-Morgan and @MariaSolovyeva - Travis repeatedly fails to build on this PR. Even though we have passed feature freeze, I would still like to get these changes merged. I am going to make a series of smaller PR's, adding the changes in incrementally. Then I will close this PR.

**Comment by Charlotte-Morgan** [comment]
:)

**Comment by timlinux** [comment]
@MariaSolovyeva Thanks for your last commit (#cf19dcd) - that is right on target in terms of what I was looking for!

For bystanders this is what it provides:

screen shot 2015-08-24 at 23 36 21

screen shot 2015-08-24 at 23 36 46

I'm making a separate PR which applies that change.

**Comment by timlinux** [comment]
Just a note that I have synchronised all these changes to my resources branch so I will probably apply them via that branch.

**Pull request merged**
