### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by ismailsunni**

### CODE REVIEW

**Comment by ismailsunni** [comment]
Hi @timlinux 
So, this is quite a strange. Suddenly, one test is failing. It's all good in my local. And we doesn't change anything.
The PR is about translation only, so it should be fine to merge it.

Best regards.

**Comment by timlinux** [comment]
@ismailsunni I'd rather we resolve the broken test before we merge....

**Comment by timlinux** [comment]
BTW its nice to cut and paste the failed tests from travis into the PR when they happen to save clicking around to find out what they were...

```
======================================================================
FAIL: Test for qgis translations.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/test/test_translations.py", line 168, in test_qgis_translations
    self.assertEqual(expected_message, real_message, message)
AssertionError: expected Tidak ada informasi gaya yang ditemukan pada lapisan %s but got No styleInfo was found for layer %s
```

**Comment by timlinux** [comment]
I tested your branch on my local machine here and can replicate the failure

**Comment by timlinux** [comment]
Have you maybe forgotten to push some files to your develop branch?

**Comment by ismailsunni** [comment]
@timlinux 
Ah yes, sorry again about the pasted failed test.

No, I have made sure everything is committed and pushed. Checked in my machine again this morning, and all is fine. But, Travis still says no :(

**Comment by ismailsunni** [comment]
Hi @timlinux

Now, it passes. I still have no idea why. I just pull from aifdr/develop, then update translation, translate the new added strings, and compile it.

Can you try it in your machine?

**Comment by timlinux** [comment]
All pass here now too - thanks @ismailsunni LGTM

**Pull request merged**
