### PR TITLE
Doc restore

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**

### CODE REVIEW

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan is the PR finished? I don't see any changes in this PR.

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni
@Timlinux did not teach me how to delete pull request yet :)

**Comment by Charlotte-Morgan** [comment]
this was just learning to make PR - there is no change because the 2nd edit put back the change in the first edit

**Comment by ismailsunni** [comment]
Just click `close pull request` button under it.
Or `close and comment` button if you want to comment before closing.

I am in github-cleaning mode. :)

**Pull request closed without merging**
