### PR TITLE
Wizard updates

### PR DESCRIPTION
**Pull request by borysiasty**

### CODE REVIEW

**Comment by borysiasty** [comment]
1. XML files filtered out from the browser
===============================
The browser is no longer cluttered by .xml files


Added an explanation why the chosen layer is unsuitable
===========================================
bad_layer

All this label is grayed out in order to indicate the layer is not selectable. The headers are bold, the mismatching keywords italic. Please note in the case above the layer is classified, while the continuous mode is required. The next line contains Continuous Hazard Unit - because my intention was to only display the **expected** unit/classification, not the one found in the layer.

**Comment by Charlotte-Morgan** [comment]
hi @borysiasty (i found the pull request :))
this looks good and provides users with helpful info +1
 - [ ] I have some reservations about barring people loading data with the correct geometry but incorrect key words (what if someone else assigned the wrong key words last time). 
- [ ] in the screen that shows there are no valid key word; can we tweak the text from "In the next step you will be able to register this layer" to In the next step you will be able to assign keywords to this  this layer" 
- [ ] i like the table approach to presenting the info - please see #2313 for some additional ideas on converting the terminology to more user friendly user facing words. I'm assuming these will also appear here in your solution

**Comment by timlinux** [comment]
> I like the table approach to presenting the info - please see #2313 for some additional ideas on converting the terminology to more user friendly user facing words. I'm assuming these will also appear here in your solution

It looks like @borysiasty is using the name property from the ```definitions.py``` so it should automatically update with tweaks you make to the presentation layer names.

**Comment by timlinux** [comment]
Ok in poking through the code it appears that my above statement is incorrect. @borysiasty we would like to standardise on using the names tor keywords terms from ```definitions.py``` so that as @Charlotte-Morgan improves them they get updated automatically in the UI.

**Comment by Charlotte-Morgan** [comment]
@timlinux - see my comments in #2313 - i did not find all the terms i need in definitions.py

**Comment by timlinux** [comment]
@Charlotte-Morgan ok I will look thanks

@borysiasty for those terms that *are* in ``definitions.py`` we can programmatically fetch them using a pattern like this (this just lists all keys).

```
import safe.definitions

for item in dir(safe.definitions):
    if not item.startswith("__"):
        var = getattr(safe.definitions, item)
        if isinstance(var, dict):
            if var.has_key('name'):
                print var['name']
```

I think we can also get rid of some of the eval statements in your code using a similar pattern. I will add a helper method to inasafe to let you get a definition whose key matches a given key.

FOr the *missing* ones @Charlotte-Morgan mentioned, I will come up with something...

**Comment by borysiasty** [comment]
Thanks @timlinux - I created another issue to not forget about the evals

**Comment by timlinux** [comment]
@borysiasty ok cool - see https://github.com/AIFDR/inasafe/pull/2328/files#diff-844316bf2c24e3915be331fde33f5059R679 for the final (re-usable) method I made to get a definition given a key. I will go ahead and apply this PR.

**Pull request merged**
