### PR TITLE
Small code convention cleanups for dock and wizard classes

### PR DESCRIPTION
**Pull request by timlinux**

### CODE REVIEW

**Comment by akbargumbira** [comment]
test this please, jenkins

**Comment by akbargumbira** [comment]
test this please, jenkins

**Comment by akbargumbira** [comment]
LGTM - The tests all ran sucessfully actually http://jenkins.inasafe.org/job/pull-request/16/console

**Comment by timlinux** [comment]
test this please, jenkins

**Comment by timlinux** [comment]
test this please, jenkins

**Comment by timlinux** [comment]
test me please, jenkins

**Pull request merged**
