### PR TITLE
Update definitions.py

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
addresses user facing names issue in  #2313 
also updates some definitions to match names and conforms to title case for names.

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
@timlinux - please review carefully. I hope nothing is broken down the line. 
I did not change anything to do with the aggregation layer so labelling there is still in full

**Comment by timlinux** [comment]
That all looks fine to me...LGTM assuming tests pass...

**Comment by timlinux** [comment]
Note that currently these tests are failing on travis:

```

======================================================================
ERROR: test_existing_complex_keywords (inasafe.safe.gui.tools.test.test_wizard_dialog.WizardDialogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 522, in test_existing_complex_keywords
    dialog.lstHazardCategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 134, in select_from_list_widget
    raise Exception(message)
Exception: There is no Multiple Event in the list widget
======================================================================
FAIL: Test if keywords already exist.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 433, in test_existing_keywords
    self.check_current_text('Single Event', dialog.lstHazardCategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 117, in check_current_text
    self.assertEqual(expected_text, current_text, message)
AssertionError: Expected Single Event but I got Single event
======================================================================
FAIL: Test for point layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 898, in test_integrated_point
    self.check_list(expected_hazard_categories, dialog.lstHazardCategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected ['Multiple Event', 'Single Event'] but I got [u'Multiple event', u'Single event']
======================================================================
FAIL: Test for polygon layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 1194, in test_integrated_polygon
    self.check_list(expected_subcategories, dialog.lstSubcategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected ['Flood', 'Tsunami', 'Earthquake', 'Volcano', 'Volcanic Ash', 'Generic'] but I got [u'Flood', u'Tsunami', u'Earthquake', u'Volcano', u'Volcanic ash', u'Generic']
======================================================================
FAIL: Test for raster layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 964, in test_integrated_raster
    self.check_list(expected_subcategories, dialog.lstSubcategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected [u'Earthquake', u'Flood', u'Volcanic Ash', u'Tsunami', u'Volcano', u'Generic'] but I got [u'Flood', u'Tsunami', u'Earthquake', u'Volcano', u'Volcanic ash', u'Generic']
======================================================================
FAIL: Test how the widgets work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 293, in test_keywords_creation_wizard
    hazard_categories, expected_hazard_categories, message)
AssertionError: Invalid hazard categories! It should be "['Single Event', 'Multiple Event']" while itwas [u'Single event', u'Multiple event']
```

**Comment by Charlotte-Morgan** [comment]
So the issue is the change I made to sentence case in three names :
Single event
Multiple event
Volcanic ash



Charlotte Morgan
Spatial Data Analyst
Australia-Indonesia Facility for Disaster Risk Reduction and
GEOSCIENCE AUSTRALIA

Mobile: +62 811 820 4648

On 5 Sep 2015, at 3:06 am, Tim Sutton <notifications@github.com<mailto:notifications@github.com>> wrote:


Note that currently these tests are failing on travis:


======================================================================
ERROR: test_existing_complex_keywords (inasafe.safe.gui.tools.test.test_wizard_dialog.WizardDialogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 522, in test_existing_complex_keywords
    dialog.lstHazardCategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 134, in select_from_list_widget
    raise Exception(message)
Exception: There is no Multiple Event in the list widget
======================================================================
FAIL: Test if keywords already exist.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 433, in test_existing_keywords
    self.check_current_text('Single Event', dialog.lstHazardCategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 117, in check_current_text
    self.assertEqual(expected_text, current_text, message)
AssertionError: Expected Single Event but I got Single event
======================================================================
FAIL: Test for point layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 898, in test_integrated_point
    self.check_list(expected_hazard_categories, dialog.lstHazardCategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected ['Multiple Event', 'Single Event'] but I got [u'Multiple event', u'Single event']
======================================================================
FAIL: Test for polygon layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 1194, in test_integrated_polygon
    self.check_list(expected_subcategories, dialog.lstSubcategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected ['Flood', 'Tsunami', 'Earthquake', 'Volcano', 'Volcanic Ash', 'Generic'] but I got [u'Flood', u'Tsunami', u'Earthquake', u'Volcano', u'Volcanic ash', u'Generic']
======================================================================
FAIL: Test for raster layer and all possibilities.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 964, in test_integrated_raster
    self.check_list(expected_subcategories, dialog.lstSubcategories)
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 90, in check_list
    self.assertItemsEqual(expected_list, real_list, message)
AssertionError: Expected [u'Earthquake', u'Flood', u'Volcanic Ash', u'Tsunami', u'Volcano', u'Generic'] but I got [u'Flood', u'Tsunami', u'Earthquake', u'Volcano', u'Volcanic ash', u'Generic']
======================================================================
FAIL: Test how the widgets work.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AIFDR/inasafe/safe/gui/tools/test/test_wizard_dialog.py", line 293, in test_keywords_creation_wizard
    hazard_categories, expected_hazard_categories, message)
AssertionError: Invalid hazard categories! It should be "['Single Event', 'Multiple Event']" while itwas [u'Single event', u'Multiple event']


-
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/pull/2333#issuecomment-137841704>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Pull request merged**
