### PR TITLE
Develop if options revisions

### PR DESCRIPTION
**Pull request by lucernae**
Includes:
- Add descriptions for IF options
- Integrate IF options error message to display
- Add constraint and grouping for Age post processor via GroupParameter

### CODE REVIEW

**Comment by lucernae** [comment]
test this please, Jenkins.

**Comment by timlinux** [comment]
I'm not sure if you were planning to take care of it in this patch, but the road type field should still be moved off to coming from the keywords, not the IF options

screen shot 2015-06-09 at 23 53 13

**Comment by timlinux** [comment]
Also @lucernae the design intent of paramters is to prevent user from making choices that are invalid. To achieve that we cant have e.g.:

screen shot 2015-06-10 at 00 04 02

Which allows user to add more classes than specified,  allows duplicate values etc. I think a collection of spinbox widgets would be more appropriate here.

**Comment by lucernae** [comment]
@timlinux about the Road type options, yes it will also be removed (that's why I didn't put any description). But since the IF still got the value from the parameters, I still include it for now. The next step would be removing that from IF options and somehow acquire it from the keywords.

and about the UI, at first I only infer it from the type of parameter that the IF expects, since it expects a list. But we can change it to spinbox like ClassifiedRasterHazardPopulationFunction

**Comment by lucernae** [comment]
test this please, Jenkins.

**Comment by lucernae** [comment]
This PR deals with issue for: #2018 to add some descriptions to IF Options
Next stage is to remove some IF options and get it from the keywords.
Right now, this stage PR is sufficient.

**Pull request merged**
